apiVersion: v1
kind: Service
metadata:
  name: fourstit-front-service
spec:
  type: NodePort
  selector:
    app: fourstit-front-label
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30032