pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata: 
              name: jenkins-agent
            spec:
              containers:
              - name: gradle
                image: gradle:8.10.0-jdk21
                command:
                - cat
                tty: true
              - name: docker
                image: docker:27.2.0-alpine3.20
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
              - name: kubectl
                image: gcr.io/cloud-builders/kubectl
                command:
                - cat
                tty: true
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
            '''
        }
    }

    environment {
        GIT_BRANCH = 'back'
        DOCKER_IMAGE_TAG = "${env.BUILD_NUMBER}"
        DISCORD_WEBHOOK = credentials('discord-webhook')
    }

    stages {
        stage('Checkout') {
            steps{
                git branch: "${GIT_BRANCH}", 
                    credentialsId: 'github_access_ssh_samdasu',
                    url: 'git@github.com:uzz99/Samdasu-Devops.git'
            }
        }

        stage('Build Backend') {
            when {
                changeset "devopsBackend/**"
            }
            steps {
                container('gradle'){
                    dir('devopsBackend') {
                        echo "Build devopsBackend Test"

                        sh 'chmod +x ./gradlew'
                        sh './gradlew clean build -x test'
                    }
                }
            }
        }

        stage('Docker Image Build'){
            when {
                changeset "devopsBackend/**"
            }
            steps {
                container('docker'){
                    script {
                        echo "DockerImageTag : ${DOCKER_IMAGE_TAG}"
                        echo "Docker Build Test"

                        sh 'docker logout'
                        withCredentials([usernamePassword(credentialsId: 'samdasu-dockerhub-access', 
                            usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD' )]){
                                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                        }

                        dir('devopsBackend') {
                            withEnv(["DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}"]){
                                sh 'docker -v'
                                sh 'docker build --no-cache -t uzz99/samdasu_repo:fourstit-back-$DOCKER_IMAGE_TAG ./'
                                sh 'docker image inspect uzz99/samdasu_repo:fourstit-back-$DOCKER_IMAGE_TAG'
                                sh 'docker push uzz99/samdasu_repo:fourstit-back-$DOCKER_IMAGE_TAG'
                            }
                        }
                        sh 'docker logout'
                    }
                }
            }
        }

        stage('Deployment'){
            when {
                changeset "devopsBackend/**"
            }
            steps{
                container('kubectl'){
                    script {

                        echo "DockerImageTag : ${DOCKER_IMAGE_TAG}"
                        
                        withEnv(["DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}"]){
                            sh 'kubectl set image deploy fourstit-back-deploy fourstit-back=uzz99/samdasu_repo:fourstit-back-$DOCKER_IMAGE_TAG -n default'
                        }
                    }
                }
            }
        }

        stage('Create Auto PR') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github_personal_access_token',
                    usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
                        sh """
                        git config user.name "$GITHUB_USER"
                        git config user.email "yj.lee991228@gmail.com"
                        git checkout ${GIT_BRANCH}
                        git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/beyond-sw-camp/be08-4th-3Dasoo.git
                        git pull origin ${GIT_BRANCH} --rebase
                        git push origin ${GIT_BRANCH}
                        curl -u $GITHUB_USER:$GITHUB_TOKEN -X POST -d '{"title":"[Backend] Auto PR: Updated Docker Tag to \\"fourstit-back-${DOCKER_IMAGE_TAG}\\"", "head":"${GIT_BRANCH}", "base":"main"}' https://api.github.com/repos/beyond-sw-camp/be08-4th-3Dasoo/pulls
                        """
                    }
                    echo "[Samdasu-Back] PR 생성 완료"
                }
            }
        }
    }
    
    post {
        success {
            withCredentials([string(credentialsId: 'discord-webhook', variable: 'DISCORD')]) {
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}s
                Docker 이미지 태그 생성: fourstit-back-${DOCKER_IMAGE_TAG}
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName} 성공", 
                webhookURL: "${DISCORD}"
            }
        }

        failure {
            withCredentials([string(credentialsId: 'discord-webhook', variable: 'DISCORD')]) {
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}s
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName} 실패", 
                webhookURL: "${DISCORD}"
            }
        }
    }
}