pipeline {
    agent any
    stages {
        // 파이프 라인의 각 단게를 관리
        stage('Checkout') {
            steps{
                git branch: 'main', 
                    credentialsId: 'github_access_ssh_samdasu',
                    url: 'git@github.com:uzz99/Samdasu-Devops.git'
            }
        }
    }
    
}