// node:18.20.4 or node:18.20.4-alpine3.20

pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata: 
              name: jenkins-agent
            spec:
              containers:
              - name: node
                image: node:18.20.4-alpine3.20
                command:
                - cat
                tty: true
              - name: docker
                image: docker:27.2.0-alpine3.20
                command:
                - cat
                tty: true
                volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: docker-socket
              - name: kubectl
                image: gcr.io/cloud-builders/kubectl
                command:
                - cat
                tty: true
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
            '''
        }
    }
    stages {
        stage('Checkout') {
            steps{
                git branch: 'main', 
                    credentialsId: 'github_access_ssh_samdasu',
                    url: 'git@github.com:uzz99/Samdasu-Devops.git'
            }
        }

        stage('Npm Install') {
            when {
                changeset "**/devopsFront/**"
            }
            steps {
                container('node') {
                    dir('devopsFront') {
                        sh 'npm i'
                    }
                }
            }
        }

        stage('Build Frontend') {
            when {
                changeset "**/devopsFront/**"
            }
            steps {
                container('node') {
                    dir('devopsFront') {
                        sh 'npm run build'
                    }
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                container('docker') {
                    script {
                        def dockerImageTag = "${env.BUILD_NUMBER}"

                        echo "DockerImageTag : ${dockerImageTag}"

                        sh 'docker logout'
                        withCredentials([usernamePassword(credentialsId: 'samdasu-dockerhub-access', 
                            usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD' )]){
                                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                        }

                        dir('devopsFront') {
                            withEnv(["DOCKER_IMAGE_TAG=${dockerImageTag}"]){
                                sh 'docker build --no-cache -t uzz99/samdasu_repo:$DOCKER_IMAGE_TAG ./'
                                sh 'docker image inspect uzz99/samdasu_repo:$DOCKER_IMAGE_TAG'
                                sh 'docker push uzz99/samdasu_repo:$DOCKER_IMAGE_TAG'
                            }
                        }
                        sh 'docker logout'
                    }
                }
            }
        }
        stage('Deployment'){
            steps{
                container('kubectl'){
                    script {
                        def dockerImageTag = "${env.BUILD_NUMBER}"
                        echo "DockerImageTag : ${dockerImageTag}"
                        
                        withEnv(["DOCKER_IMAGE_TAG=${dockerImageTag}"]){
                            sh 'kubectl set image deploy fourstit-front-deploy nginx=uzz99/samdasu_repo:fourstit-front-$DOCKER_IMAGE_TAG -n default'
                        }
                    }
                }
            }
        }
    }
    
    post {
        success {
            withCredentials([string(credentialsId: 'samdasu-discord-webhook', variable: 'DISCORD')]) {
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}s
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName} 성공", 
                webhookURL: "${DISCORD}"
            }
        }

        failure {
            withCredentials([string(credentialsId: 'samdasu-discord-webhook', variable: 'DISCORD')]) {
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}s
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName} 실패", 
                webhookURL: "${DISCORD}"
            }
        }
    }
}